# tenforflow warm-up

In [1]:
import tensorflow as tf
# create variable
W = tf.Variable([[0.5, 1.0]])
x = tf.Variable([[2.0], [1.0]])
y = tf. matmul(W, x)
print("in tensorflow, the data format of y is {0}".format(y))
init_op = tf.global_variables_initializer()
with tf.Session() as sess:
    sess.run(init_op)
    print("the value of y = {0}".format(y.eval()))

H:\anaconda_env\anaconda_install\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


in tensorflow, the data format of y is Tensor("MatMul:0", shape=(1, 1), dtype=float32)
the value of y = [[2.]]


# create different dim of tensor

In [8]:
# 输出一个tensor的值有两种方式，第一种是使用eval，第二种是使用sess.run
with tf.Session() as sess:
    constant_zeros = tf.zeros([3, 4], dtype = tf.float32)
    print("constant_zeros = {0}".format(constant_zeros.eval()))
    constant_zeros_like = tf.zeros_like(constant_zeros)
    print("the new constant_zeros = {0}".format(constant_zeros_like.eval()))
    constant_ones = tf.ones(shape = [3, 4], dtype = tf.int32)
    print("the full-one matrix = {0}".format(constant_ones.eval()))          #   方式一  
    constant_ones_like = tf.ones_like(constant_ones)
    print("the ones-like matrix = {0}".format(sess.run(constant_zeros_like))) # 方式二
    # create tensor-1D
    tensor_1D = tf.constant([1, 2, 3, 4, 5])
    print("for the tensor of 1 dim = {0}".format(tensor_1D.eval()))
    # create tensor-2D
    tensor_2D =  tf.constant(3.0, shape = [2, 3])
    print("for the tensor of 2 dim = {0}".format(sess.run(tensor_2D)))
    # create number sequence
    num_seq = tf.linspace(10.0, 12.0, 3)     # 等差数列
    print("the equal difference series = {0}".format(num_seq.eval()))
    # create a list 
    tf_list = tf.range(3, 15, 3)
    print("the list in tensorflow is similar to numpy, the value is {0}".format(sess.run(tf_list)) )

constant_zeros = [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
the new constant_zeros = [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
the full-one matrix = [[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
the ones-like matrix = [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
for the tensor of 1 dim = [1 2 3 4 5]
for the tensor of 2 dim = [[3. 3. 3.]
 [3. 3. 3.]]
the equal difference series = [10. 11. 12.]
the list in tensorflow is similar to numpy, the value is [ 3  6  9 12]


# we can create different distribution in tensorflow, such as Gaussian

In [13]:
with tf.Session() as sess:
    std_norm = tf.random_normal([2, 3], mean = 0., stddev = 1.)
    print("the standard gaussian distribution, value = {0}".format(sess.run(std_norm)))
    constant_shuffle = tf.random_shuffle(tf.constant([[1, 2], [3, 4], [5, 6]]))
    print("shuffle a tensor, the value = {0}".format(sess.run(constant_shuffle)))

the standard gaussian distribution, value = [[ 0.25636742 -1.5764154   1.638669  ]
 [-0.8690325  -1.893317   -1.4236875 ]]
shuffle a tensor, the value = [[3 4]
 [1 2]
 [5 6]]


# 使用tensorflow来实现 for loop

In [14]:
state = tf.Variable(0)
new_value = tf.add(state, tf.constant(1))
update = tf.assign(state, new_value)       # update the value of state
init_op = tf.global_variables_initializer()    # 一旦使用到了variable 就必须进行全局初始化
with tf.Session() as sess:                 
    sess.run(init_op)
    print(sess.run(state))
    for _ in range(3):                     # 全局执行，从创建变量处就开始运行程序
        sess.run(update)
        print(sess.run(state))

0
1
2
3


# tensoflow中的保存方式Saver

In [15]:
# 使用tf,train.Saver来保存数据到文件中
W = tf.Variable([[0.5, 1.0]])
x = tf.Variable([[2.0], [1.0]])
y = tf.matmul(W, x)
init_op = tf.global_variables_initializer()
saver = tf.train.Saver()     # 创建Saver类的实例对象
with tf.Session() as sess:
    sess.run(init_op)
    '''
    在使用tensorflow 来训练模型时，将模型的设计和训练部分在此处实现
    此处省略若干步
    '''
    save_path = saver.save(sess, ".//model_variable//")     # 保存到当前目录下的model_variable文件夹下
    print("Model Variable in file: {0}".format(save_path))  # 输出数据保存的文件夹的路径

Model Variable in file: .//model_variable//


# numpy 中的ndarray和tensorflow 中的tensor的相互转化

In [16]:
import numpy as np
a = np.zeros((3, 3))
trans_a = tf.convert_to_tensor(a)
with tf.Session() as sess:
    print("after transform, the value = {0}".format(sess.run(trans_a)))
    print("trans_a's info: {0}".format(trans_a))

after transform, the value = [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
trans_a's info: Tensor("Const_7:0", shape=(3, 3), dtype=float64)


# tensorflow中的placeholder

In [17]:
input_1 = tf.placeholder(dtype = tf.float32)     # 在创建占位符的时候，就跟其他语言一样，需要指定此处占位的数据的类型
input_2 = tf.placeholder(dtype = tf.float32)
output = tf.multiply(input_1, input_2)
with tf.Session() as sess:
    product_result = sess.run(output, feed_dict = {input_1:7.0, input_2:10.0})    # 给占位的数据赋值
    print("the product result = {0}".format(product_result))

the product result = 70.0
